# Numpy

El objeto más importante de numpy es un arreglo multidimensional y homogéneo llamado ndarray. Se trata de una tabla de elementos donde todos son del mismo 'tipo' que pueden ser perfectamente identificados por un índice de pares de enteros (i,j). En Numpy las dimensiones de dicho arreglo se llaman 'axis' y el número total de dimensiones que tiene un arreglo se llama 'rank'.

In [1]:
import numpy as np

In [5]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Atributos de un ndarray

In [7]:
a.shape

(3, 5)

In [8]:
a.ndim

2

In [9]:
a.dtype.name

'int64'

In [10]:
a.itemsize

8

In [11]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [14]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [15]:
type(b)

numpy.ndarray

## Crear ndarrays y tipo

Es importante notar que a la hora de crear un ndarray el 'tipo' de los datos lo va a determinar el intérprete de Python a menos que lo indiquemos explícitamente

In [17]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [19]:
a.dtype

dtype('int64')

In [21]:
b = np.array([1.2, 3.5, 5.1])
b

array([ 1.2,  3.5,  5.1])

In [22]:
b.dtype

dtype('float64')

Un error común es tratar de definir un ndarray a partir de serie números y no a partir de una lista

In [23]:
a = np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [24]:
a = np.array([1,2,3,4])

Secuencias de secuencias se transforman en ndarrays de dos dimensiones, secuencias de secuencias de secuencias se transforman en ndarrays de tres dimensiones y así sucesivamente. El ejemplo de secuencias más común que hemos visto son las listas.

In [25]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [26]:
b.dtype

dtype('float64')

Se puede indicar explícitamente el 'tipo' del ndarray utilizando el parámetro opcional dtype

In [27]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [29]:
d = np.array( [ [1,2], [3,4] ], dtype=int )
d

array([[1, 2],
       [3, 4]])

Hay arreglos que podemos generar de manera predeterminada dentro de numpy con las funciones zeros y ones

In [30]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [31]:
np.ones( (2,3,4), dtype=float )

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

Analogamente a la función range(), numpy tienne su propia función llamada arange() como vimos arriba.

In [34]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [35]:
np.arange( 0, 2, 0.3 ) #Noten que acepta argumentos del tipo float 

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

Una alternativa común a la función range() es utilizar la función linspace() que tiene la ventaja de que le podemos indicar el número de argumentos que queremos de vuelta, lo que no siempre es posible calcular utilizando arange() dada la precisión de los datos del tipo float 

In [36]:
np.linspace( 0, 2, 9 ) # 9 números del 0 al 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [39]:
from numpy import pi
x = np.linspace( 0, 2*pi, 100 ) 
x

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [41]:
f = np.sin(x).round(2)
f

array([ 0.  ,  0.06,  0.13,  0.19,  0.25,  0.31,  0.37,  0.43,  0.49,
        0.54,  0.59,  0.64,  0.69,  0.73,  0.78,  0.81,  0.85,  0.88,
        0.91,  0.93,  0.95,  0.97,  0.98,  0.99,  1.  ,  1.  ,  1.  ,
        0.99,  0.98,  0.96,  0.95,  0.92,  0.9 ,  0.87,  0.83,  0.8 ,
        0.76,  0.71,  0.67,  0.62,  0.57,  0.51,  0.46,  0.4 ,  0.34,
        0.28,  0.22,  0.16,  0.1 ,  0.03, -0.03, -0.1 , -0.16, -0.22,
       -0.28, -0.34, -0.4 , -0.46, -0.51, -0.57, -0.62, -0.67, -0.71,
       -0.76, -0.8 , -0.83, -0.87, -0.9 , -0.92, -0.95, -0.96, -0.98,
       -0.99, -1.  , -1.  , -1.  , -0.99, -0.98, -0.97, -0.95, -0.93,
       -0.91, -0.88, -0.85, -0.81, -0.78, -0.73, -0.69, -0.64, -0.59,
       -0.54, -0.49, -0.43, -0.37, -0.31, -0.25, -0.19, -0.13, -0.06, -0.  ])

## Cómo se imprimen los arrays de numpy

In [43]:
a = np.arange(6) # Array de una dimensión
print(a)

[0 1 2 3 4 5]


In [44]:
b = np.arange(12).reshape(4,3)  # Array de dos dimensiones
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [46]:
c = np.arange(24).reshape(2,3,4) # Array de tres dimensiones
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

¿Cómo puedo revisar el número de dimensiones de los ndarrays de arriba?

In [49]:
c.ndim

3

## Operaciones básicas con ndarrays

In [50]:
a = np.array( [20,30,40,50] )

In [52]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [54]:
# Cuánto da c?
c = a-b
c

array([20, 29, 38, 47])

In [55]:
b**2

array([0, 1, 4, 9])

In [56]:
a<35

array([ True,  True, False, False], dtype=bool)

### Multiplicación elemento por elemento y matricial

In [58]:
A = np.array( [[1,1],[0,1]] )
print(A)

[[1 1]
 [0 1]]


In [60]:
B = np.array( [[2,0],[3,4]] )
print(B)

[[2 0]
 [3 4]]


In [61]:
#Operación elemento por elemento
A*B 

array([[2, 0],
       [0, 4]])

In [62]:
#Producto Matricial
A.dot(B)

array([[5, 4],
       [3, 4]])

### Continuamos con más Operaciones Básicas

Podemos utilizar las operaciones += y *= y que estas se persistan en el objeto ndarray

In [67]:
a = np.ones((2,3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [68]:
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

### Random en Numpy

Una de las mejores cosas es numpy es su capacidad para generar números aleatorios. Vamos a ver la línea de código debajo y revisamos la documentación de numpy.

In [69]:
a = np.random.random((2,3))
a

array([[ 0.88048765,  0.61009538,  0.82972074],
       [ 0.51659177,  0.85879851,  0.8220116 ]])

In [70]:
a.sum()

4.5177056418735884

In [71]:
a.min()

0.51659177021690128

In [72]:
a.max()

0.88048765354032721

Por default estas operaciones se aplican a todos los elementos de la matriz como si fueran una 'lista' de números. Sin embargo, se les puede aplicar operaciones por fila o por columna si indicamos la dimensión o 'axis' sobre los que queremos realizar la operación

In [74]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
b.sum(axis=0) #Suma de cada columna

array([12, 15, 18, 21])

In [76]:
b.min(axis=1) #Mínimo de cada fila

array([0, 4, 8])

In [77]:
b.cumsum(axis=1) #Expliquemos Cumsum

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### Universal Functions

Parte del poder de Numpy son una serie de funciones que vienen por default que se llaman 'Universal Functions'. Básicamente se refiere a funciones matemáticas preprogramadas que nos permiten hacer operaciones comunes de una manera 1) más legible y rápida y 2) con un procesamiento más eficiente de nuestros datos.

In [80]:
B = np.arange(3)
B

array([0, 1, 2])

In [81]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [83]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [86]:
C = np.array([2., -1., 4.])
C

array([ 2., -1.,  4.])

In [87]:
np.add(B,C)

array([ 2.,  0.,  6.])

## Slicing

In [90]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [91]:
a[2]

8

In [92]:
a[2:5]

array([ 8, 27, 64])